import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex-col "
      style={{
        fontFamily: "Arial",
        margin: 0,
        padding: 0,
        background: "#111111 url(page/bgr.png) no-repeat center center / cover",
        // marginLeft: "5%",
      }}
      >
        {children}
      </body>
    </html>
  );
}
